name: Lint Code Base

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
  checks: write

jobs:
  lint:
    name: Run Super Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Git Super Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true  
          FAIL_ON_ERROR: false          
          RUN_JSCPD: false              
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
